### ISSUE TITLE
Work out-of-the-box

### ISSUE THREAD

**Issue by Milo123459** [tokio-rs/console#122]
Hey,

This looks absolutely amazing and I definitely want to use this on all my apps. However, I feel like this should be a tool that works out of the box, ie, any asynchronous code (tokio::spawn, etc) should be displayed without having to create tasks.

This is my personal opinion, but I'm open to suggestions, and discussions!

**Comment by hawkw** [comment]
Hi @Milo123459,

I'm not totally sure what you mean by working "out of the box". If you mean that users shouldn't have to explicitly annotate or wrap tasks in order for them to be tracked by the console, that's already the case! 

The instrumentation that the console depends on is provided by the runtime itself, not by your code. Currently, only Tokio exposes this instrumentation, but we hope to see support added in other runtimes as well --- and not just for async runtimes: console support for `rayon` is also planned.  All you have to do is add
```rust
console_subscriber::init();
```
in your `main` function to enable the console, and everything should work.

**Comment by Milo123459** [comment]
Alright, I got a little confused, my bad. 

Just to be clear, you don't have to only use tasks for it to display?

**Comment by hawkw** [comment]
> Just to be clear, you don't have to only use tasks for it to display?

I'm not totally sure what you mean here. The console tracks all async tasks created by functions like `tokio::spawn` (and `tokio::runtime::Handle::spawn`, `tokio::task::spawn_blocking`, `tokio::task::spawn_local`, etc). [Tasks are the fundamental unit of concurrency](https://docs.rs/tokio/1.11.0/tokio/task/index.html#what-are-tasks) in all asynchronous Rust programs; if you're writing async code, you're almost certainly already using tasks. 

If you're wondering whether the console is aware of the individual futures that _compose_ to form tasks, the console instrumentation doesn't currently track futures within tasks, only the spawned tasks themselves.

**Comment by Milo123459** [comment]
I'm stupid, sorry.
