### ISSUE TITLE
Running the console in alacritty blocks selections and copy-paste

### ISSUE THREAD

**Issue by meithecatte** [tokio-rs/console#167]
My guess is that the terminal is led to believe that a mouse-supporting application is running. I'm not aware of any mouse features in the tokio console, though.

**Comment by hawkw** [comment]
Yeah, I think that `tui` does this by default. I'd like to add mouse support in the future, but until then, we should probably figure out how to not make it do that...

**Comment by hawkw** [comment]
#222 should fix this!
