### ISSUE TITLE
Specify a custom port when serving

### ISSUE THREAD

**Issue by Milo123459** [tokio-rs/console#183]
Just a simple option for serving the server on a custom port. Useful for docker containers with specific ports needing to be used.

**Comment by hawkw** [comment]
Does this method work?

https://github.com/tokio-rs/console/blob/a30264e0b5469ea596430b846b05e6e3541915d1/console-subscriber/src/builder.rs#L97-L106

**Comment by Milo123459** [comment]
Oh, didn't see. I will test later.

**Comment by Milo123459** [comment]
How do I call that? Is there example usage?

For example,
`console_subscriber::build().server_addr()` doesnt' work.

**Comment by hawkw** [comment]
The `Builder` type is used to construct a `TasksLayer`. `build()` does significantly more than constructing a `TasksLayer`, it also creates a subscriber and spawns it on a background thread. `build()` calls `TasksLayer::builder()` internally: https://github.com/tokio-rs/console/blob/a30264e0b5469ea596430b846b05e6e3541915d1/console-subscriber/src/init.rs#L137

We should probably make these APIs work nicer together...we could add a version of `build()` that takes a custom `TasksLayer` `Builder`, or add a method to the builder type that's equivalent to `build()` but using the builder's custom configurations. Honestly, I think there are some aspects of the subscriber-construction API that we should probably rethink before publishing a `console-subscriber` crates.io release...

For now, as a workaround, you can copy the code from `build()` into your project, and call `server_addr` on the `Builder` here: https://github.com/tokio-rs/console/blob/a30264e0b5469ea596430b846b05e6e3541915d1/console-subscriber/src/init.rs#L137

**Comment by Milo123459** [comment]
Just copy everything from build?

PS: Something in an ideal world that would work: `build().server_addr(...).init()`

**Comment by seanmonstar** [comment]
Isn't there also `TOKIO_CONSOLE_BIND` as an environment variable?
