### ISSUE TITLE
Finished tasks sometimes stay in the console and appear busy

### ISSUE THREAD

**Issue by daladim** [tokio-rs/console#189]
Thanks for this great tool, that I'm using to have insights on a large app that spawns many tasks.

When I run the console long enough, it eventually displays busy tasks that run forever.
![image](https://user-images.githubusercontent.com/6873361/144449233-3a2a9145-77c1-4234-b250-8d29634e704b.png)

However, I'm quite positive all these tasks are finished. Indeed, these tasks are spawned via 
```rust
tokio::task::Builder::new().name(some_name).spawn(some_async_function)
```
and they all have reached the last line of `some_async_function`, where I added a `println!("Finished task {}", some_task_id)` that actually got displayed.

So that looks either like a tokio bug that did not joined the task after it reached its last line, or a bug in the console-subscriber that misses some "task is finished" events (or in tokio-console that does not process them).

# Ideas to create a minimal reproducer
Have a function that spams tasks, that all complete after some time (let's say after a random (sync or async) sleep between 1 and 40s).
I could try to write it myself if that could be helpful to you.
I am building and running on Win10 if that matters

**Comment by zaharidichev** [comment]
>  I could try to write it myself if that could be helpful to you.

@daladim  that would be super useful!

**Comment by hawkw** [comment]
Is it possible that these tasks have completed, but have not yet been _dropped_? Are the `JoinHandle`s for these tasks stored in a data structure of some kind?

**Comment by colinjfw** [comment]
I think I was able to reproduce something similar, if you run the following example for ~2 minutes or so with the latest commit I start to see the idle task count continually increasing.

Theoretically this code should be dropping all of the task handles correctly.

```
use std::time::Duration;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    console_subscriber::init();
    
    loop {
        let mut tasks = Vec::new();
        for _ in 0..5 {
            let task = tokio::task::spawn(async {
                println!("hello");
            });
            tasks.push(task);
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
        for t in tasks {
            t.await.unwrap();
        }
        println!("awaited");
    }
}
```

**Comment by hawkw** [comment]
@colinjfw interesting, thanks for the repro!

**Comment by daladim** [comment]
Thanks for doing what I did not have to time do lately :-)
Also, I wasn't totally sure my code did not keep `JoinHandle`s here and there, so that's interesting to see you can reproduce even if your code does drop them

**Comment by hawkw** [comment]
I believe #238 fixes this issue. Are you able to try the latest git revision of `console-subscriber` (fdc77e28d45da73595320fab8ce56f982c562bb6) and confirm that this is the case? You'll also need to build the git version of the console CLI.

**Comment by daladim** [comment]
That's much better now, I no longer see this bug.

Thanks for your work! I'm closing the issue.

**Comment by hawkw** [comment]
Great, thank you!
