### ISSUE TITLE
work items before publishing to crates.io

### ISSUE THREAD

**Issue by pnkfelix** [tokio-rs/console#193]
This is a tracking issue to gather work items to do as part of a prep for posting a pre-1.0 release of console-subscriber and console (presumably with a different name) to crates.io 

 * [x] Pick a name (`tokio-console-*` is current front-runner in Discord chat) 
 * [x] "fix the separate build and TaskLayer::builder APIs": https://github.com/tokio-rs/console/issues/183#issuecomment-969301688
     * race between PR #195 and PR #196.
 * [x] Land resources PR https://github.com/tokio-rs/console/pull/188
 * [x] Document the public API https://github.com/tokio-rs/console/issues/194
 * [x] PR preparing release
 * [x] Manually test that process written in release notes works (do this after push to crates.io but before adding release notes to tokio.rs)!

**Comment by hawkw** [comment]
Done! :D
