### ISSUE TITLE
doc: document public API

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/console#194]
The console-subscriber crate should have their public API documented using the Tokio documentation style. For an example, see [`runtime::Builder`](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/builder.rs).

This should be done by Thursday, December 16th to meet the 0.1 release date.

Tasks:
 * [x] document console-api: PR #197 
 * [x] document console-subscriber: PR #198
 *  ~~document public API of console crate itself~~ the  `console` crate has no public programmatic API

**Comment by pnkfelix** [comment]
Hmm. Apparently `tonic` escapes things like square brackets in comments when it generates doc-comments.

(That's probably meant to be *helping* me, e.g. if I were writing a comment that wanted to use square brackets for a sequence or an index expression. But I don't know how to cajole it into making hyper-links in the generated doc with this.)

That's okay though, we can live without rustdoc hyperlinks in the tonic-generated docs.

**Comment by hawkw** [comment]
> Hmm. Apparently `tonic` escapes things like square brackets in comments when it generates doc-comments.
> 
> (That's probably meant to be _helping_ me, e.g. if I were writing a comment that wanted to use square brackets for a sequence or an index expression. But I don't know how to cajole it into making hyper-links in the generated doc with this.)
> 
> That's okay though, we can live without rustdoc hyperlinks in the tonic-generated docs.

this feels like it might be worth an upstream feature request (i think against `prost`, which does the actual code generation)...but it's not a blocker.

**Comment by pnkfelix** [comment]
This is done now that PRs #197 and #198 have landed.
