### ISSUE TITLE
Report when a task doesn't / hasn't yielded in a while.

### ISSUE THREAD

**Issue by tobz** [tokio-rs/console#203]
While using `tokio-console` for debugging some weird behavior -- by the way, `tokio-console` has been great so far! -- I ended up discovering that my original issue was related to a task that never yielded.  While `tokio-console` helped me figure this out by displaying that a companion task hadn't yet been woken up (because of the other task not yielding), it would have saved me a step or two if instead I was able to see that the non-yielding task hadn't yielded in a while/at all.

Not sure if this is simple to surface or not, but figured I'd file an issue for it regardless. :)

**Comment by hawkw** [comment]
This should be pretty easy. I think the only difficult part is that we'll have to determine how long a task should have run before yielding before adding a warning.

**Comment by hawkw** [comment]
@tobz if you're interested in working on this, the way we'd do it is adding a new type implementing the `Warn` trait: https://github.com/tokio-rs/console/blob/7d16eadc5c254f21b0f4fba31f2fdf758808a8f4/console/src/warnings.rs#L4-L47

This would be pretty similar to existing warnings, like `SelfWakePercent`: https://github.com/tokio-rs/console/blob/7d16eadc5c254f21b0f4fba31f2fdf758808a8f4/console/src/warnings.rs#L118-L135

I think that in the check method for this, we'd want to flag a task for the warning if *all* of the following are true:

1. it is currently active (so the warning doesn't fire for tasks that are waiting to run)
2. it has never yielded
3. it has been running for a period of time >= some threshold (configurable?)

**Comment by hawkw** [comment]
we probably want to be _fairly_ generous with the threshold, to avoid false positives...it could be something like 5-10 ms? I don't think we want the lint to fire on particularly short-lived tasks; if a task only has two or three await points in it, it's entirely possible that one instance of that task might just be lucky enough that they're all ready, and that's _fine_ if it runs for like, 1ms or less!

**Comment by hawkw** [comment]
@tobz still planning on working on this?

**Comment by tobz** [comment]
As interesting as it may be, I think my spare time is a bit too small at
the moment to take this. :(

**Comment by fbrv** [comment]
Hi there,
I'm learning Tokio and Rust and I think this issue could be interesting for me, if no one else is working on that I could give it a try

**Comment by hawkw** [comment]
@fbrv sorry i didn't reply sooner --- are you still interested in working on this issue? If so, please feel free to open a PR, or let me know if you have any questions!

**Comment by rybertm** [comment]
Hi @hawkw, I'm considering working on this if I can, but have a question, my assumptions may be wrong so forgive me if that's the case.

> I think that in the check method for this, we'd want to flag a task for the warning if all of the following are true:
it is currently active (so the warning doesn't fire for tasks that are waiting to run)
it has never yielded
it has been running for a period of time >= some threshold (configurable?)

Does checking if a task is running and for longer than the threshold check all 3?

My assumptions being:
1. It is currently active - Meaning it is not awakened nor completed. Is an idle task considered active?
2. It has never yielded - Meaning it is still running

**Comment by jefftt** [comment]
Hi! I saw that this went a little stale so I opened up a PR, happy to take feedback on it! Thanks

**Comment by yerke** [comment]
Since https://github.com/tokio-rs/console/pull/439 got merged, should this issue be closed?

**Comment by 0xPoe** [comment]
Yes. I think we can close it now. Thank you!
