### ISSUE TITLE
subscriber: consider adding filter env var builder parameter

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#206]
>what do you think about making the filter environment variable a builder parameter? so, by default, it uses `RUST_LOG`, but there's a separate builder method to change the filter env var? something like:
>
>```rust
>let console = console_subscriber::Builder::new()
>    .with_filter_env_variable("MYAPP_LOG")
>    .build_console_layer();
>```
>
> _Originally posted by @hawkw in https://github.com/tokio-rs/console/pull/195#discussion_r769848327_

**Comment by hi-rustin** [comment]
I am working on this.
