### ISSUE TITLE
console: emoji/symbols glossary

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#225]
When the terminal supports Unicode, the console CLI will use a number of emojis and other symbols as icons etc. This is good, because it's easier to visually scan the UI this way, and in many cases, it uses fewer characters, allowing more screen real estate for things like paths that are potentially long. However, in some cases, the precise meaning of a particular emoji may not be _quite_ as obvious as text. We might want to add some kind of glossary explaining the meanings of some of the emoji/symbols we use.

This could be in the documentation, or somewhere in the UI itself (a floating help window you toggle by pressing a key?)

**Comment by bIgBV** [comment]
A floating help window in general would be a good idea. It could be part of building the glossary I think.

**Comment by bIgBV** [comment]
Looking at the code and thinking a spending some more time thinking about the implementation: 

Different views would have different help information to display (including the glossary of emojis if they are being used), which pertains specifically to the view. If every view had a way to display help information (probably in the bottom row in one or two lines) then we could hook the event handler to display the right help information based on the current view state.

**Comment by bIgBV** [comment]
I looked into whether or not it was possible to do floating windows using corssterm, but it doesn't look like there's an easy way to do that.

**Comment by javihernant** [comment]
I think this can be closed as PR [#432 ](https://github.com/tokio-rs/console/pull/432) was already merged

**Comment by jonatan-zeidler-bl** [comment]
The modal help view prints the controls, but does not explain emojis/symbols as of #432. I don't think, this should be closed.
