### ISSUE TITLE
Example app in console-subscriber doesn't build

### ISSUE THREAD

**Issue by hardliner66** [tokio-rs/console#252]
The app example in console-subscriber fails because it's trying to use task::Builder which is non existent.

**Comment by hawkw** [comment]
`tokio::task::Builder` is an [unstable `tokio` API](https://docs.rs/tokio/latest/tokio/index.html#unstable-features). This means you need to build with the environment variable `RUSTFLAGS="--cfg tokio_unstable"`. 

In general, the console relies on unstable features in Tokio (the `tracing` support that powers the console is also unstable). So, to use the console, you will need to enable `--cfg tokio_unstable`. See [here](https://github.com/tokio-rs/console/tree/main/console-subscriber#enabling-tokio-instrumentation) for details.

There's a [`.cargo/config` file](https://github.com/tokio-rs/console/blob/main/.cargo/config) in this repository that _should_ automatically enable this flag when building inside the console repo (such as building the examples). I'm surprised that didn't work for you --- did you move the example app to another directory before trying to build it?

**Comment by iulianR** [comment]
I also hit this problem just now. While looking for the solution I came across this other issue: https://github.com/rust-lang/cargo/issues/5376#issuecomment-925951786. In my case, I have this in my `~/.cargo/config.toml`:
```
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
```
Commenting the `rustflags` in there solves the problem.

**Comment by hawkw** [comment]
Oh, that makes sense; the working directory's `.cargo/config` `rustflags` setting isn't combined with the global `.cargo/config`'s. That seems mildly surprising...

**Comment by hardliner66** [comment]
I have the same settings set in my `~/.cargo/config`.

Currently it seems that the more specific `[target.x86_64-unknown-linux-gnu]` in `~/.cargo/config` overrides the more generic `[build]` in the current project. If you change the local `.cargo/config` to `[target.x86_64-unknown-linux-gnu]` instead of `[build]` it properly combines with the settings from `~/.cargo/config`.

So in order for it to work properly for all targets you can set `rustflags` for each triple where you or a teammate uses a custom `rustflags` setting.

e.g.:
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable"]
```

This isn't ideal, but can be worked around. Depending on your use case, it might make sense to just add the tokio settings to the global config file instead and enable it everywhere.

**Comment by hawkw** [comment]
@hardliner66 oh, that's interesting! Perhaps we should add `[target.<TARGET>]` settings to the `.cargo/config` in this repo so that the examples works. We should probably do this for all common targets, so that it also works if, for example, people are building on MacOS and have per-target rustflags overrides...

**Comment by hardliner66** [comment]
It should at least be documented as a gotcha, but having a copy-paste ready example for the most common targets sounds reasonable.

**Comment by hawkw** [comment]
The documentation has been updated to warn about this, so I'm going to close this issue now.
