### ISSUE TITLE
subscriber: poll ops appear to basically be a memory leak

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#256]
AFAICT, when poll ops are recorded, they appear to never go away: https://github.com/tokio-rs/console/blob/4ec26a8d535674c7906d6e42c2633d4f24a524a5/console-subscriber/src/aggregator/mod.rs#L86-L87

we should probably fix this.

**Comment by zaharidichev** [comment]
True, will fix that.

**Comment by Milo123459** [comment]
#184 might be related?

**Comment by hawkw** [comment]
> #184 might be related?

It's certainly possible!

@zaharidichev are you planning to work on a fix for this, or should I start on it at some point?

**Comment by ttys3** [comment]
Oh, this confused me for days. thanks for confirm the leak problem.

From my Prometheus graph, I see the leak is very slow, but took a day can see it very obviously

below is just a service only has a `/healthz` api response `ok` string and with console subscriber enabled:

![2022-03-15_00-21](https://user-images.githubusercontent.com/41882455/158215967-3621d64b-230d-4051-8adc-8b5f4d3314c1.png)
