### ISSUE TITLE
invalid homepage

### ISSUE THREAD

**Issue by Emilgardis** [tokio-rs/console#280]
https://github.com/tokio-rs/console/blob/fd309c048c98d20bd83b3c10b4f0b8fa8a5f80ba/tokio-console/Cargo.toml#L10

homepage points to non-existent resource

should be 

```toml
homepage = "https://github.com/tokio-rs/console/tree/main/tokio-console" 
```

**Comment by hawkw** [comment]
Whoops, good catch!
