### ISSUE TITLE
Make rustfmt optional

### ISSUE THREAD

**Issue by jyn514** [tokio-rs/console#298]
I got this error building console-api just now:
```
error: failed to run custom build command for `console-api v0.1.0`

Caused by:
  process didn't exit successfully: `/home/jnelson/work/redacted/target/debug/build/console-api-fe07466b9cc39039/build-script-build` (exit status: 1)
  --- stderr
  error: 'rustfmt' is not installed for the toolchain '1.58-x86_64-unknown-linux-gnu'
  To install, run `rustup component add rustfmt --toolchain 1.58-x86_64-unknown-linux-gnu`
```
Rustfmt shouldn't be strictly necessary for console to build - could you make the build script handle the error gracefully instead of raising a hard error?

**Comment by hawkw** [comment]
I believe we can do this by disabling [the `rustfmt` feature flag on the `tonic-build` dependency](https://docs.rs/tonic-build/latest/tonic_build/#features).

**Comment by hawkw** [comment]
...huh, that's weird, it looks like the `rustfmt` feature _is_ disabled, since we depend on `tonic-build` with `default-features = false`: https://github.com/tokio-rs/console/blob/80d7f4250ee5add0965ff100668be21d20621114/console-api/Cargo.toml#L40-L43

**Comment by hawkw** [comment]
FWIW, it looks like `tonic-build` will completely drop the runtime `rustfmt` dependency in the next release: https://github.com/hyperium/tonic/pull/904

**Comment by jyn514** [comment]
Ah, this is my fault, sorry - I had another dependency that depended on tonic-build and didn't disable the default features. Cargo unified the feature between the other dependency and `console`.
