### ISSUE TITLE
console: handle disconnection more gracefully

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#30]
right now, if the console is connected to a server, and the server disconnects abruptly, we immediately crash with a big error message:
```
:; cargo run
   Compiling console-subscriber v0.1.0 (/home/eliza/Code/consolation/console-subscriber)
    Finished dev [unoptimized + debuginfo] target(s) in 0.69s
     Running `target/debug/console`
using default address (http://127.0.0.1:6669)
Error:
   0: status: Unknown, message: "h2 protocol error: broken pipe", details: [], metadata: MetadataMap { headers: {} }

Location:
   console/src/main.rs:52

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮
   6: console::main::{{closure}}::h0f02eae7993e30df
      at /home/eliza/Code/consolation/console/src/main.rs:52
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h89be4d09d64d3ea1
      at /home/eliza/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
   8: tokio::park::thread::CachedParkThread::block_on::{{closure}}::h8f240001a5901c1b
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263
   9: tokio::coop::with_budget::{{closure}}::h3c95765523460448
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:106
  10: std::thread::local::LocalKey<T>::try_with::hab4856318f2607b4
      at /home/eliza/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272
  11: std::thread::local::LocalKey<T>::with::h3d4d9732c38fcac6
      at /home/eliza/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248
  12: tokio::coop::with_budget::h54da439ec06757dd
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:99
  13: tokio::coop::budget::h9ae2f64aafef4b99
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:76
  14: tokio::park::thread::CachedParkThread::block_on::h045a83290eb58c9b
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263
  15: tokio::runtime::enter::Enter::block_on::hdddd13bfd62fbbcb
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/enter.rs:151
  16: tokio::runtime::thread_pool::ThreadPool::block_on::h7920c3eacc3339a7
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/mod.rs:71
  17: tokio::runtime::Runtime::block_on::h678a88f6df65c487
      at /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/mod.rs:452
  18: console::main::hdbffd1488c60b5c6
      at /home/eliza/Code/consolation/console/src/main.rs:17
  19: core::ops::function::FnOnce::call_once::hf4e9e56d9a430675
      at /home/eliza/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
                                ⋮ 11 frames hidden ⋮

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```
(this is after i `ctrl-c`'d the example app).

We should probably handle connection errors a little more gracefully --- if the user is debugging something when the app crashes or there's a network issue, it's almost certainly better to continue showing the last state and add a message saying "hey, the connection to the remote ended abruptly, here's why".

Eventually, it would also be good to try to reconnect with a backoff period, so that we can recover from transient network issues.

**Comment by zaharidichev** [comment]
@hawkw Is there something generic that can be used that works with a backoff or we need to put in place something like the [reconnect in Linkerd](https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/reconnect/src/lib.rs)

**Comment by hawkw** [comment]
We can probably use [`tower`'s `reconnect` middleware](https://docs.rs/tower/0.4.8/tower/reconnect/struct.Reconnect.html), but it doesn't implement backoffs, so we would have to implement that part ourselves --- there may be other crates in the ecosystem that I'm not personally aware of.

It does seem like support for backoffs is something that's worth having upstream in `tower::reconnect`. I might open an issue for that.

For now, I would start with handling the error nicer in the UI --- we probably want to continue displaying the last state and add a message at the top that says we lost the conenction to the remote application. Then, we can add reconnection (with a backoff) in a follow-up.

**Comment by hawkw** [comment]
**Update**: oh, it turns out there already is an issue for adding backoffs to tower (https://github.com/tower-rs/tower/issues/60) ...and it was opened by me, three years ago. :sweat_smile:

**Comment by zaharidichev** [comment]
> Update: oh, it turns out there already is an issue for adding backoffs to tower (tower-rs/tower#60) ...and it was opened by me, three years ago. 😅

Yeah :) Forgot to mention that. Okey, I will add the nicer state handling then.

**Comment by seanmonstar** [comment]
Looks like this was done in #57, so I'm going to close :)
