### ISSUE TITLE
console: add missing configuration options to the config file

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#331]
### What problem are you trying to solve?

Currently, some configuration options can only be set from the command line: the target address, the console log filter, and the retention interval. This is because these fields are only present on the `Config` struct, and not the `ConfigFile` struct:

https://github.com/tokio-rs/console/blob/3a67d476835e4a1d3557190b85f5a89c760490bb/tokio-console/src/config.rs#L23-L69

It should probably be possible to set at least some of these values from the config file, as well.

### How should the problem be solved?

We should probably add these values to the `ConfigFile` struct and support setting them in the config file.

### Any alternatives you've considered?

I'm somewhat on the fence as to whether it makes sense to set the target address in the config file. I think it makes sense, given that the current config overriding system means that the config file would be setting the _default_ target address, and it would be overridden by the CLI. So, it might make sense to name the config key for this `default_target_addr` or similar.

### Would you like to work on this feature?

maybe

**Comment by hawkw** [comment]
@nrskt perhaps you'd be interested in working on this one as well?

**Comment by nrskt** [comment]
thanks, I'm interesting this work. I’ll take it😁
