### ISSUE TITLE
subscriber: record and send a histogram of Task poll times

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#36]
We currently send the total elapsed time that a task spends inside its `poll` function, but it'd be helpful to also include more statistics. This would help to see average poll time, which would make it easier to identify tasks that are "blocking" too long in their `poll` functions. It would also help to identify when only _sometimes_ a poll takes too long. And we could eventually use this data in the console to show a warning of tasks with poll times that are too high.

Using a histogram to record this seems like a good balance, since a simple average can lose the spikiness of some polls. I imagine we can use something like [hdrhistogram](https://crates.io/crates/hdrhistogram).

**Comment by hawkw** [comment]
per @jonhoo, I believe `hdrhistogram` is also compact enough that we should be able to have a fairly small wire representation for sending them to the console.

**Comment by oguzbilgener** [comment]
This sounds like fun. I have some free time these days and if no one else is working on this already, I'd like to take this on. :)

**Comment by seanmonstar** [comment]
You got it! Let us know if you have questions here, or you can join the `#console` channel at discord.gg/tokio.
