### ISSUE TITLE
console: task view: show poll time percentiles

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#38]
This depends on #36. Once the subscriber is sending the poll times as a histogram, the task instance view (the one viewing just a single task in more detail) should include the percentiles of the poll times, at least p50 and p99 (perhaps p25, and p90 are also useful?).

**Comment by hawkw** [comment]
I think that the `tui` crate also has some tools for drawing graphs, so perhaps we could eventually show the entire histogram, as well as the most important percentiles. But we should start with just showing the numbers.

**Comment by seanmonstar** [comment]
Done in #47
