### ISSUE TITLE
Add key to jump from an async op to the related task

### ISSUE THREAD

**Issue by hds** [tokio-rs/console#448]
### What problem are you trying to solve?

In the resource detail view, there is a table of async ops associated with the resource. The user can move up and down to highlight a specific resource. However, going straight to the associated task isn't easy.

<img width="1040" alt="tokio-console-screenshot-2023-July-7-60416" src="https://github.com/tokio-rs/console/assets/89589/39dfc693-dda0-4360-9dc1-c22f680627a2">

### How should the problem be solved?

It would be nice to be able to press a key and jump to that task in the tasks list view, or a different key and jump straight to the task's detail view.

### Any alternatives you've considered?

We could also open a modal view with the task details in there.

### How would users interact with this feature?

Perhaps the `return` key could be used to jump to the task in the task list. This would mean that hitting return twice would result in jumping on to the details view. Alternatively (or in addition), a specific key (`d` for details?) could take the user straight to the task details view.

**Comment by hawkw** [comment]
something like this would definitely be nice to have!
