### ISSUE TITLE
Sorting does not work on all columns in the resources view

### ISSUE THREAD

**Issue by AEnterprise** [tokio-rs/console#488]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

When using the resources view the sorting does not work on the following columns:
- parent
- target
- type
- vis
- location
- attributs

### How can the bug be reproduced?

Just using the tokio console to display metrics from a application with some different types of locks/channels

### Versions

tokio-console 0.1.10

### Would you like to work on fixing this bug?

maybe

**Comment by hawkw** [comment]
Sounds like a bug, thanks for the report!

I'm assuming the other columns in the resources view do work for sorting?

**Comment by AEnterprise** [comment]
Yes the other columns work fine
