### ISSUE TITLE
`tokio-console` won't quit when the main program has exit

### ISSUE THREAD

**Issue by eval-exec** [tokio-rs/console#495]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

`tokio-console`'s tui won't quit if I press `q` key. This happens after the main program has exit.

### How can the bug be reproduced?

1. Start a `console_subscriber::init();` in a `main.rs`
2. Start `tokio-console`
3. let main.rs quit
4. press `q` on `tokio-console`'s ui, but the ui doesn't quit

### Versions

```text
❯ cargo tree | grep console-
├── console-subscriber v0.2.0
│   ├── console-api v0.6.0

❯ tokio-console --version
tokio-console 0.1.10

```

### Would you like to work on fixing this bug?

yes

**Comment by hds** [comment]
@eval-exec Was thsi issue closed on purpose? I wasn't able to reproduce locally.
