### ISSUE TITLE
subscriber: add grpc-web support to console-subscriber

### ISSUE THREAD

**Issue by 0xPoe** [tokio-rs/console#497]
### What problem are you trying to solve?

Currently, we only support standard gRPC. However, if we aim to develop a web console in the browser, it will require the use of [grpc-web](https://github.com/grpc/grpc-web) to connect to the console-subscriber. Since grpc-web only supports HTTP 1.1, we cannot directly connect to the console-subscriber. To facilitate this, we must use [envoy](https://www.envoyproxy.io/) as a proxy for forwarding. While this approach is effective, it introduces a new component to the system.

### How should the problem be solved?

Because tonic has [`tonic-web`](https://github.com/hyperium/tonic/tree/master/tonic-web) layer, we can add a new feature to help users to enable it. Then we can connect the console-subscriber with grpc-web. I have implemented it. It worked well.

### Any alternatives you've considered?

Use envoy as a proxy to workaround.

### How would users interact with this feature?

Users only need to enable the `grpc-web` or `web` feature.

### Would you like to work on this feature?

yes

**Comment by hawkw** [comment]
This seems like a good idea to me! A web console would be neat to have eventually!

**Comment by yerke** [comment]
@hi-rustin since https://github.com/tokio-rs/console/pull/498 got merged, should this issue be closed?

**Comment by 0xPoe** [comment]
Yes, I think we can close it now.

**Comment by 0xPoe** [comment]
Thank you
