### ISSUE TITLE
Format "last woken" time prettily

### ISSUE THREAD

**Issue by hds** [tokio-rs/console#524]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

Tokio console has nice prettily formatted times when UTF-8 support is turned on.

The times use only a small number of decimal places and are colour coded depending on the multiplier (seconds, milliseconds, etc.).

However, in the Task detail screen in the Waker panel, there is a time for "last woken" which does not have this formatting. It is not color-coded and it generally displays far too many decimal places.

### How can the bug be reproduced?

Enter the task detail screen for a task that has been woken at least once. Look at the Waker panel, specifically the "last woken" value.

See screenshot for details and a comparison of the pretty vs. non-pretty times:

![tokio-console-last_woken_time](https://github.com/tokio-rs/console/assets/89589/03da78f7-cc33-4ff1-8994-879fa1be403d)

### Versions

tokio-console: 0.1.10 (and also the [`main`](https://github.com/tokio-rs/console/tree/28a27fcfeb3a0838e1f5f2d17a6fa18b3f33c508) branch at the time of writing).

### Possible solution

Change the formatting of the value for "last woken":
https://github.com/tokio-rs/console/blob/28a27fcfeb3a0838e1f5f2d17a6fa18b3f33c508/tokio-console/src/view/task.rs#L208

See the value for the "total time" field in the Task panel for an example of how to format the time prettily:
https://github.com/tokio-rs/console/blob/28a27fcfeb3a0838e1f5f2d17a6fa18b3f33c508/tokio-console/src/view/task.rs#L183

**Comment by devanbenz** [comment]
I can take this one on

**Comment by hds** [comment]
Unassigned @devanbenz, that was a mistake.

**Comment by yerke** [comment]
Hi @hds. I created https://github.com/tokio-rs/console/pull/529 to address this. Do you mind taking a look?

**Comment by hds** [comment]
> Hi @hds. I created #529 to address this. Do you mind taking a look?

@yerke Yes,looks good, It might not get merged until Monday though.
