### ISSUE TITLE
Analyze log files and log playback

### ISSUE THREAD

**Issue by cathaysia** [tokio-rs/console#532]
### What problem are you trying to solve?

In many scenarios, my program runs for a very short time. I hope to manually collect the program's logs and then input them to the console for playback.

### How should the problem be solved?

log playback

### Any alternatives you've considered?

no

### Would you like to work on this feature?

maybe

**Comment by hds** [comment]
Thanks for your issue!

We already have a tracking ticket for this request: #70. We have some initial implementation for recording (#84), but no playback yet.

I'm going to close this as a duplicate, we'll be tracking this work under #70 going forward. If you're interested in contributing, please reach out on that ticket or in the Tokio Discord!
