### ISSUE TITLE
tokio-console cannot show the pause status correctly

### ISSUE THREAD

**Issue by 0xPoe** [tokio-rs/console#551]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

There are two Tokio Console instances connected to the same stream. If you pause the stream in one instance and the status cannot be displayed correctly in the other instance.

### How can the bug be reproduced?

All steps execute under the git repo:

1. Start the example app: `cargo run --example app`
2. Start one tokio console: `cargo run`
3. Start another tokio console: `cargo run`
4. Hit `space` in one of the instances
<img width="1354" alt="image" src="https://github.com/tokio-rs/console/assets/29879298/430a79d8-5b3a-4f1b-a736-b189ea9067f9">
As you can see, all of them are paused, but only one of them showed `PAUSED`.

### Versions

```text
commit 3193fde77adf1473c4124adfa6ef8234659589c9 (origin/main, origin/HEAD)
Author: 二手掉包工程师 <rustin.liu@gmail.com>
Date:   Mon Apr 22 21:35:21 2024 +0800

    chore: run clippy against all targets (#546)
    
    This would help us to check if there are any
    clippy warning in the tests.
```

### Possible solution

Perhaps we should include a new API to allow clients to check whether the stream has been paused.

### Additional context

I believe the reason for this problem is that we only store the pause status on the client side. Therefore, there is no way to notify other instances to know the stream is paused.

### Would you like to work on fixing this bug?

yes

**Comment by 0xPoe** [comment]
@hds @hawkw Do you have any thoughts about this problem? Maybe we should include the status in the state stream, or add a new API to allow clients to query the status?

**Comment by hds** [comment]
I need to check the API, because I don't remember how it's set up currently. But ideally the status would be sent as part of the regular updates which are pushed from the `console-subscriber` server to `tokio-console`. This would serve as acknowledgement for the client that paused the session and would also inform other clients that the session has been paused and that they won't receive further updates until it is unpaused.

What do you think @hi-rustin?

**Comment by 0xPoe** [comment]
> This would serve as acknowledgement for the client that paused the session and would also inform other clients that the session has been paused and that they won't receive further updates until it is unpaused.


Do you mean we always push the paused state on updates? If we only push it once, then the new client will not get it if it tries to connect to the server after the server has been paused.

**Comment by hds** [comment]
A new client should always receive at least one update, which would indicate that the state is "Paused" in this case.

**Comment by 0xPoe** [comment]
> A new client should always receive at least one update, which would indicate that the state is "Paused" in this case.

Sounds good. I will try to add it.
