### ISSUE TITLE
Crash when selecting a task that no longer exists

### ISSUE THREAD

**Issue by RaphaelMarinier** [tokio-rs/console#565]
I reliably encounter the crash below while running tokio console.
To reproduce:
- Have tasks ordered in descending order.
- Select the last task with 'G'
- Wait for the task to disappear (of course, it means you need to instrument a binary with a varying number of tasks).
- Push enter.
- The crash below occurs.

## Error
```
index out of bounds: the len is 58 but the index is 18446744073709551601
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.10|
|**config.subcmd**|`None`|
|**config.target_addr**|`None`|
|**config.env_filter**|`None`|
|**config.log_directory**|`None`|
|**config.retain_for**|`None`|
|**config.view_options.no_colors**|`false`|
|**config.view_options.lang**|`Some("en_US.UTF-8")`|
|**config.view_options.ascii_only**|`None`|
|**config.view_options.truecolor**|`Some(true)`|
|**config.view_options.palette**|`None`|
|**config.view_options.toggles.color_durations**|`None`|
|**config.view_options.toggles.color_terminated**|`None`|
|**location**|/home/raphael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-console-0.1.10/src/view/table.rs:166:34|

**Comment by 0xPoe** [comment]
I will take a look.

**Comment by 0xPoe** [comment]
I can reproduce it. I will try to fix it.
