### ISSUE TITLE
`tokio-console` fails to compile

### ISSUE THREAD

**Issue by leontoeides** [tokio-rs/console#569]
### What crate(s) in this repo are involved in the problem?

tokio-console

### What is the issue?

Fails to compile when using `cargo install --locked tokio-console`

### How can the bug be reproduced?

Compiling `tokio-console` on Windows.

### Logs, error output, etc

```
error[E0635]: unknown feature `stdsimd`
  --> C:\Users\User\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ahash-0.8.6\src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tokio-console v0.1.11`, intermediate artifacts can be found at `C:\Users\USER\AppData\Local\Temp\cargo-install0n0qyL`.
```

### Versions

Check your `Cargo.toml` files ;-)

### Possible solution

I believe that bumping your dependencies (which also would bump their `ahash` dependency) may fix this

### Would you like to work on fixing this bug?

no

**Comment by 0xPoe** [comment]
I cannot reproduce this issue on my Windows 11.
![image](https://github.com/tokio-rs/console/assets/29879298/1a12657c-6f76-44d4-9e21-c7cf1f865f66)
```log
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
```log
$ cargo -Vv
cargo 1.78.0 (54d8815d0 2024-03-26)
release: 1.78.0
commit-hash: 54d8815d04fa3816edc207bbc4dd36bf18014dbc
commit-date: 2024-03-26
host: x86_64-pc-windows-msvc
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 Professional) [64-bit]
```

**Comment by piano1029** [comment]
Hello, I am able to reproduce this issue on an Apple Silicon MacBook running MacOS 14.5 (23F79).

@hi-rustin The stdsimd feature got split into multiple sub-features (https://github.com/rust-lang/rust/issues/48556), your version of Rust is out of date, as such you do not have this issue. Installing your version of the toolchain (1.78.0-aarch64-apple-darwin in my case) through rustup results in tokio-console compiling just fine. Please update your version of Rust through rustup in order to re-produce this issue.

```
cargo 1.81.0-nightly (154fdac39 2024-07-07)
release: 1.81.0-nightly
commit-hash: 154fdac39ae9629954e19e9986fd2cf2cdd8d964
commit-date: 2024-07-07
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.6.0 (sys:0.4.73+curl-8.8.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.5.0 [64-bit]
```

**Comment by 0xPoe** [comment]
Thanks! I have filed https://github.com/tokio-rs/console/issues/569 to fix it.
