### ISSUE TITLE
subscriber: structured span fields

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#6]
right now, we just capture all span fields as a string. we should probably fix this

**Comment by zaharidichev** [comment]
@hawkw  I can do that if it is fine.

**Comment by hawkw** [comment]
> @hawkw I can do that if it is fine.

sure! at one point, i started working on the protobuf additions to do this; if you like, i can push up that change and you can take it from there, although i can't promise whether or not that will end up being useful.

**Comment by hawkw** [comment]
okay @zaharidichev here's the branch where i started working on this: https://github.com/tokio-rs/console/compare/eliza/structured?expand=1

feel free to pick it up from there if you like. one note is that i think it would be nice to be able to encode statically known fields as indices into the field set in a span's metadata, rather than as strings, on the wire. although we may want to save that for a follow-up change, it could be good to reserve the ability to add it to the protobuf later.

**Comment by zaharidichev** [comment]
makes sense, given it is early days, can we get rid of the string representation field in the proto message now or we want to keep it around?

**Comment by hawkw** [comment]
it would be fine to remove the string field from the proto, i think, since we're not currently making any stability guarantees for the proto...feel free to get rid of it when you have structured fields working end to end
