### ISSUE TITLE
Build fails on Mac M1

### ISSUE THREAD

**Issue by joelreymont** [tokio-rs/console#62]
```
   Compiling h2 v0.3.3
error: failed to run custom build command for `console-api v0.1.0 (/Users/joelr/Work/Rust/console/console-api)`

Caused by:
  process didn't exit successfully: `/Users/joelr/Work/Rust/console/target/debug/build/console-api-509b6171e0106590/build-script-build` (exit status: 1)
  --- stderr
  Error: Custom { kind: Other, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): Bad CPU type in executable (os error 86)" }
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by carllerche** [comment]
Hmm, this looks like a `prost` issue, cc @LucioFranco

**Comment by LucioFranco** [comment]
I don't have a M1 mac to test on but seems related to https://github.com/protocolbuffers/protobuf/issues/8062? That said, this error seems like it may be with how prost invokes `protoc`. I've read some stuff that ZSH may be related but I don't know and can't test it right now.

**Comment by joelreymont** [comment]
@LucioFranco any tips for how I can troubleshoot this on my own?

**Comment by joelreymont** [comment]
By the way, the Protobuf issue is about _precompiled binaries_, it builds from source just fine

https://github.com/protocolbuffers/protobuf/issues/8062#issuecomment-730047763

**Comment by LucioFranco** [comment]
@joelreymont I guess the main question is can you invoke `protoc --version`?

**Comment by joelreymont** [comment]
> @joelreymont I guess the main question is can you invoke `protoc --version`?

I sure can! 

```
❯ protoc --version
libprotoc 3.17.3
```

**Comment by LucioFranco** [comment]
Interesting, I think there is something going on with how m1 mac runs its binaries https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable kinda gives a hint but honestly I am not sure what the fix is here..

That said, maybe its looking for a binary with the wrong name? https://github.com/tokio-rs/prost/blob/5d93c55426d9c219fb1fb065adfa8fd3e43833a1/prost-build/build.rs#L59

**Comment by joelreymont** [comment]
The zsh error is about trying to run ARM binaries and not having the emulator installed. I don't have it installed precisely to catch issues like this one!

I just checked out Prost, let me see if I can fix this...

**Comment by joelreymont** [comment]
> That said, maybe its looking for a binary with the wrong name? https://github.com/tokio-rs/prost/blob/5d93c55426d9c219fb1fb065adfa8fd3e43833a1/prost-build/build.rs#L59

Yes, this is the issue! How do I submit a pre-built `protoc` for bundling? Just stick it under `./prost-build/third-party/protobuf/`?

**Comment by joelreymont** [comment]
I'm gonna patch `tonic` to use my local copy of `prost`, just to test my fix. Then I'll submit the PR to `prost` and, hopefully, it will be the end of it. @carllerche @LucioFranco anything else?

**Comment by LucioFranco** [comment]
@joelreymont a patch PR works great! Just tag me in the PR and ill take a look.

**Comment by joelreymont** [comment]
This should fix it https://github.com/tokio-rs/prost/pull/508
