### ISSUE TITLE
Create a view of Resources

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/console#63]
As we instrument resources (sockets, files, timers, etc) (#39), we want a view to visualize them, seeing related attributes and states, such as what task they currently "belong" to.

**Comment by seanmonstar** [comment]
I was playing with some fake data and came up with this potential mock-up:

![console-resources-view](https://user-images.githubusercontent.com/51479/125328613-62f6af00-e2f9-11eb-9044-f9858477f02a.PNG)

**Comment by pnkfelix** [comment]
One important detail/goal here is that in an ideal world, a user would be able to distinguish "Task A is waiting on Resource" from "Task B currently using Resource", and that in turn from "One of tasks C or D responsible for eventually replenishing Resource." (I can imagine in the general case it may not be feasible to actually supply all that info, especially the latter in a very dynamic system. But I can dream!)

**Comment by seanmonstar** [comment]
Agreed, this will be especially useful for things like channels or locks, where we know one task is doing something that will affect another waker.

**Comment by hawkw** [comment]
I believe this was implemented in #188.
