### ISSUE TITLE
The trait bound `TasksRequest: prost::message::Message` is not satisfied

### ISSUE THREAD

**Issue by joelreymont** [tokio-rs/console#66]
I'm on a Mac M1 and fixed the #62 in my local fork of `prost`. 

I then hacked `tonic` to point to my local fork of of `prost` and my local fork of `console` to point to local fork of `tonic`. Still, I'm getting this build error. 

What's the correct way to set up for development? 

Do I edit `Cargo.toml` all over the place and edit the dependencies, then clean it all up before packaging?

```
   Compiling hyper-timeout v0.4.1
   Compiling tonic v0.5.0 (/Users/joelr/Work/Rust/tonic/tonic)
error[E0277]: the trait bound `TasksRequest: prost::message::Message` is not satisfied
   --> /Users/joelr/Work/Rust/console/target/debug/build/console-api-d4acf0bef599edb6/out/rs.tokio.console.tasks.rs:157:2649
    |
157 | ...ks") ; self . inner . server_streaming (request . into_request () , path , codec) . await } pub async fn watch_task_details (& mut sel...
    |                          ^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `TasksRequest`
    |
    = note: required because of the requirements on the impl of `Codec` for `ProstCodec<TasksRequest, _>`
```

**Comment by hawkw** [comment]
> What's the correct way to set up for development?
> 
> Do I edit `Cargo.toml` all over the place and edit the dependencies, then clean it all up before packaging?

The easiest way to override a dependency with a development version is to use [Cargo's `[patch]` section](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html). The nice thing about using `[patch]` (rather than hand-editing `Cargo.toml`s) is that it patches _all_ dependencies on a crate in the project's dependency tree. 

This means you *should* be able to put something like this in the root `Cargo.toml` in the `console` repo:
```toml
[patch.crates.io]
prost = { git = "https://github.com/joelreymont/prost", branch = "the-branch-your-changes-are-on" }
prost-build = { git = "https://github.com/joelreymont/prost", branch = "the-branch-your-changes-are-on" }
prost-types = { git = "https://github.com/joelreymont/prost", branch = "the-branch-your-changes-are-on" }
```
and it should replace all `prost` dependencies, including `tonic`'s --- a `tonic` fork shouldn't be necessary if you're using `[patch]`.

If that doesn't fix the errors, let me know!

**Comment by joelreymont** [comment]
It's close but... 😢 

```
   Compiling console-api v0.1.0 (/Users/joelr/Work/Rust/console/console-api)
error[E0433]: failed to resolve: use of undeclared type `InterceptedService`
   --> /Users/joelr/Work/Rust/console/target/debug/build/console-api-d4acf0bef599edb6/out/rs.tokio.console.tasks.rs:157:1641
    |
157 | ...Send + Sync , { TasksClient :: new (InterceptedService :: new (inner , interceptor)) } # [doc = r" Compress requests with `gzip`."] # ...
    |                                        ^^^^^^^^^^^^^^^^^^ use of undeclared type `InterceptedService`
```

`InterceptedService` is in tonic but not 0.4?

**Comment by hawkw** [comment]
> It's close but... cry
> 
> ```
>    Compiling console-api v0.1.0 (/Users/joelr/Work/Rust/console/console-api)
> error[E0433]: failed to resolve: use of undeclared type `InterceptedService`
>    --> /Users/joelr/Work/Rust/console/target/debug/build/console-api-d4acf0bef599edb6/out/rs.tokio.console.tasks.rs:157:1641
>     |
> 157 | ...Send + Sync , { TasksClient :: new (InterceptedService :: new (inner , interceptor)) } # [doc = r" Compress requests with `gzip`."] # ...
>     |                                        ^^^^^^^^^^^^^^^^^^ use of undeclared type `InterceptedService`
> ```
> 
> `InterceptedService` is in tonic but not 0.4?

hmm... make sure that you're using the same version of both `tonic` and `tonic-build`?

**Comment by joelreymont** [comment]
Making a bit of progress here... 

`console` specifies `tonic 0.4` and `prost 0.7` whereas the latest versions are `0.5` and `0.7` respectively. I had to update the version numbers in various `console` cargo files for the patches to be used.

I'm at a loss about this one, though. Trying to figure it out but it positively has to do with the version upgrade!

```
   Compiling console v0.1.0 (/Users/joelr/Work/Rust/console/console)
error[E0277]: the trait bound `SystemTime: From<Timestamp>` is not satisfied
   --> console/src/tasks.rs:116:41
    |
116 |             self.last_updated_at = Some(now.into());
    |                                         ^^^^^^^^^^ the trait `From<Timestamp>` is not implemented for `SystemTime`
    |
    = help: the following implementations were found:
              <SystemTime as From<httpdate::date::HttpDate>>
    = note: required because of the requirements on the impl of `Into<SystemTime>` for `Timestamp`
```

**Comment by seanmonstar** [comment]
We've since upgraded to tonic v0.5, would this be all fixed with that?

**Comment by seanmonstar** [comment]
I'm going to assume this is indeed fixed.
